---

- name: Install Java
  yum:
    state=latest
    name={{ item }}
  with_items: "{{ cassandra_java_packages }}"

- name: Import DataStax GPG Key
  rpm_key:
    state=present
    key=http://rpm.datastax.com/rpm/repo_key

- name: Install DataStax Repo
  template:
    src=datastax.repo
    dest=/etc/yum.repos.d/datastax.repo
    mode=0644

- name: Install Cassandra
  yum:
    state=latest
    name=datastax-ddc
